const { cakeActions } = require("../cake/cakeSlice").default;
const createSlice = require("@reduxjs/toolkit").createSlice;

const initialState = {
  numOfIceCreams: 13,
};

// reducers from one createSlice will respond to only actions generated by that createSlice
const iceCreamSlice = createSlice({
  name: "iceCream",
  initialState,
  reducers: {
    ordered: (state) => {
      state.numOfIceCreams--;
    },
    restocked: (state, action) => {
      state.numOfIceCreams += action.payload;
    },
  },
  //   extraReducers: {
  //     ["cake/ordered"]: (state) => {
  //       state.numOfIceCreams--;
  //     },
  //   },
  // Recomended method: extraReducers build function
  extraReducers: (builder) => {
    builder.addCase(cakeActions.ordered, (state) => {
      state.numOfIceCreams--;
    });
  },
});

module.exports = iceCreamSlice.reducer; // Defaul export
module.exports.iceCreamActions = iceCreamSlice.actions; // Named export
